#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

runApplication blockMesh

runApplication setFields

# Run the NeoFOAM incompressibleVoF solver (interFoam-style VoF)
neofoam solver incompressiblevof > log.incompressibleVoF 2>&1
# Alternative: runApplication interFoam

#------------------------------------------------------------------------------
