#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------
touch pitzDaily.foam
restore0Dir

runApplication blockMesh
#runApplication decomposePar

# mpirun -np 4 foamadapter solver pimpleFoam -parallel
# runApplication foamadapter solver pimpleFoam
# runParallel "foamadapter solver pimplefoam"
runApplication neofoam solver incompressiblefluid

# runApplication pimpleFoam

#------------------------------------------------------------------------------
