#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------
restore0Dir

runApplication blockMesh
runApplication neofoam solver incompressiblefluid

# The tables declared in system/postProcess.yaml and system/postProcess.py:
#   postProcessing/volume_p.csv          postProcessing/volume_p_script.csv
#   postProcessing/volume_U_scaled.csv   postProcessing/volume_U_script.csv
#   postProcessing/volume_p_clipped.csv

#------------------------------------------------------------------------------
