[project]
name = "neofoam"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Henning Scheufler", email = "henning.scheufler@web.de" }
]
requires-python = ">=3.9"

dependencies = [
    "pybFoam>=0.3.1",
    "typer",
    "pydantic>=2.0.0",
    "networkx>=3.0",
    "matplotlib>=3.0.0",
    "pyvis>=0.3.2",
    "neon_pde",
]

[project.optional-dependencies]
dev = [
    "pytest>=6.0",
    "pytest-cov",
    "pytest-xdist",
    "pydantic-settings",
    "black",
    "flake8",
    "isort",
    "mypy",
    "pandas>=2.0.0",
    "poethepoet>=0.37.0",
    "ruff>=0.14.2",
    "mypy",
    "pre-commit",
]
docs = [
    "sphinx>=4.0",
    "myst-parser",
    "sphinx-sitemap",
    "furo",
    "sphinxcontrib-mermaid",
    "breathe",
]
all = [
    "neofoam[dev,docs]",
]

[project.scripts]
neofoam = "neofoam.cli.app:app"

[build-system]
requires = [
    "scikit-build-core[pyproject]>=0.11.0",
    "nanobind>=2.9.0",
]
build-backend = "scikit_build_core.build"

[tool.scikit-build]
cmake.version = ">=3.22"
cmake.args = ["--preset=python-bindings"]
build.verbose = true
build-dir = "_skbuild"
editable.mode = "redirect"
editable.verbose = true
editable.rebuild = false

[tool.scikit-build.cmake.define]
NEOFOAM_BUILD_PYTHON_BINDINGS = "ON"

[tool.uv.sources]
neon_pde = { path = "src/NeoN", editable = true }


[tool.ruff]
line-length = 100
target-version = "py39"
extend-exclude = ["build/", "dist/"]

[tool.ruff.lint]
select = ["E","F","I"]  # enable isort (I) + basic lint

# optional per-rule ignores
ignore = []

# isort options (import sorting)
[tool.ruff.lint.isort]
known-first-party = ["neofoam"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra --showlocals"
testpaths = [
    "test"
]

[tool.mypy]
files = ["src", "test"]          # your two roots
mypy_path = ["src"]              # so imports from src resolve
strict = true                    # optional but recommended
no_site_packages = true          # don't check installed packages

# Exclude src/Neon and everything beneath it
# (mypy applies this regex to the normalized file path)
exclude = [
  "src/NeoN",
]

# If other code imports src/NeoN and you want mypy to never follow into it:
[[tool.mypy.overrides]]
module = ["NeoN", "NeoN.*", "pybFoam", "pybFoam.*", "neon", "neon.*"]
ignore_missing_imports = true
follow_imports = "skip"

[tool.poe.tasks]
test = "pytest"
lint = "ruff check src test"
format = "ruff format src test"
type_check = "mypy src test"
build_docs = "sphinx-build -b html doc doc/_build"
view_docs = { shell = "python -m webbrowser -t doc/_build/index.html" }
