version = 1
SPDX-PackageName = "NeoN"
SPDX-PackageSupplier = "NeoN authors"
SPDX-PackageDownloadLocation = "https://github.com/exasim-project/NeoN"

[[annotations]]
path = [
    ".github/**",  ".vscode/**.json", "README.md",  "CHANGELOG.md", "AUTHORS.md",  "doc/**"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 NeoN authors"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
    "CMakePresets.json", ".clang-format", ".clang-tidy", ".pre-commit-config.yaml", "spack.yaml", "REUSE.toml", "scripts/san_ignores.txt", "CITATION.cff"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 - 2024 NeoN authors"
SPDX-License-Identifier = "Unlicense"
