version = 1
SPDX-PackageName = "NeoFOAM"
SPDX-PackageSupplier = "NeoFOAM authors"
SPDX-PackageDownloadLocation = "https://github.com/exasim-project/NeoFOAM"

[[annotations]]
path = [
    ".github/**", "AUTHORS.md",  "doc/**"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 NeoFOAM authors"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
    "CMakePresets.json", ".clang-format", ".clang-tidy", ".pre-commit-config.yaml", "spack.yaml", "REUSE.toml",  ".vscode/**.json", "*.log", ".claude/**", "CLAUDE.md"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 - 2024 NeoFOAM authors"
SPDX-License-Identifier = "Unlicense"

[[annotations]]
path = [
    "test/**",
     "benchmarks/**",
     "tutorials/**",
     "examples/**",
     ".github/workflows/build.yaml",
     ".github/workflows/static_checks.yaml",
     ".github/workflows/pubkey.gpg",
     ".vscode/c_cpp_properties.json",
     ".vscode/settings.json",
     "CHANGELOG.md",
     "README.md",
     "AGENTS.md",
     "CLAUDE.md",
     ".claude/**",
     ".gitmodules",
     ".coverage",
     "environment.yml",
    "CMakePresets.json",
    ".clang-format",
    ".clang-tidy",
    ".pre-commit-config.yaml",
    "spack.yaml",
    "**/case/**",
    "REUSE.toml",
    "ruff.toml",
    "pyproject.toml",
    "uv.lock"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 - 2025 NeoFOAM authors"
SPDX-License-Identifier = "Unlicense"
