version = 1
SPDX-PackageName = "NeoFOAM"
SPDX-PackageSupplier = "NeoFOAM authors"
SPDX-PackageDownloadLocation = "https://github.com/exasim-project/NeoFOAM"

[[annotations]]
path = [
    ".github/**",  ".vscode/**.json", "README.md",  "CHANGELOG.md", "AUTHORS.md",  "doc/**"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 NeoFOAM authors"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
    "CMakePresets.json", ".clang-format", ".clang-tidy", ".pre-commit-config.yaml", "spack.yaml", "REUSE.toml", "scripts/san_ignores.txt", "CITATION.cff"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 - 2024 NeoFOAM authors"
SPDX-License-Identifier = "Unlicense"
