#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

touch BenardCells.foam

restore0Dir

runApplication blockMesh

# runApplication decomposePar

runApplication $(getApplication)

# runApplication python icoFoam.py

#------------------------------------------------------------------------------
