#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

application="interFoam"

restore0Dir

runApplication blockMesh

runApplication ${application}

#------------------------------------------------------------------------------
