#!/bin/bash
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

touch hotRoom.foam
restore0Dir

runApplication blockMesh

runApplication setFields

# Boussinesq model auto-detected from transportProperties (beta, TRef)
foamadapter solver incompressiblefluid > log.foamadapter 2>&1
# runApplication buoyantBoussinesqPimpleFoam

#------------------------------------------------------------------------------
