#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

./Allrun.pre

runApplication decomposePar

restore0Dir -processor

# Test polling interfaces
# runParallel $(getApplication) -opt-switch nPollProcInterfaces=-1
runParallel $decompDict ../../../build/productionM2Max/bin/neoSimpleFoam -parallel

runApplication reconstructPar

#------------------------------------------------------------------------------
