#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase0
rm -rf processor*
rm -f constant/triSurface/tiltedCube.stl
rm -f constant/triSurface/tiltedCube.eMesh
rm -rf constant/extendedFeatureEdgeMesh
rm -f  *.foam

#------------------------------------------------------------------------------
