#!/bin/bash -l
### Script for running the open-closed coolings DrivAre with a static mesh
### Original authors: Charles Mockett, Hendrik Hetmann and Felix Kramer (Upstream CFD GmbH), 2022-2023
### Modified setup for OpenFOAM HPC Challenge (OHC-1): Mark Wasserman (Huawei) and Sergey Lesnik (Wikki GmbH), 2025

# Based on the geometry and setup of the AutoCFD4 Workshop:
# Hupertz, B., Chalupa, K., Krueger, L., Howard, K., Glueck, H.-D., Lewington, N., . . . Shin, Y.-s. (2021). On the Aerodynamics of the Notchback Open Cooling DrivAre: A Detailed Investigation of Wind Tunnel Data for Improved Correlation and Reference. SAE Int. J. Adv. & Curr. Prac. in Mobility, 3(4), 1726-1747. doi:https://doi.org/10.4271/2021-01-0958

### example for slurm submission
# adapt to your needs or ignore if not submitting to a queuing system
#SBATCH --job-name "DrivAre_RANS"
#SBATCH --ntasks=512
#SBATCH --ntasks-per-node=128
#SBATCH --partition=arm
#SBATCH --output=%x-%j.out
#SBATCH --error=%x-%j.err

### Solver
solverRANS="simpleFoam"

### Used directories
logDir="logFiles"

### Misc
fvSolution=fvSolution.fixedIter # fvSolution.fixedTol
controlDict=controlDict.noWrite # controlDict.withWrite
fileHandler=" "                 # "-fileHandler hostCollated "

# function to read parameters from caseDefinition...
function getInputParam ()
{
    varVal=`grep -w ${1} system/include/caseDefinition | cut -d ";" -f 1 | grep -v '//'`
    varVal=`echo ${varVal:${#1}}`
    echo $varVal
}

# get input parameters
nProcs=`getInputParam nCores`
TIMESTAMP=$(date "+%Y-%m-%d_%H-%M-%S")

# copy controlDict/fvSolution files

cp system/${controlDict} system/controlDict
cp system/${fvSolution} system/fvSolution

# extra mpi flags
OMPI_FLAGS="" #  "--mca pml ucx"

parEx="mpirun -np ${nProcs} ${OMPI_FLAGS}"


. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions

# ---- initialise & run simulation
mkdir $logDir
echo; echo "decomposePar"
time decomposePar -constant $fileHandler > $logDir/10_decomposePar.log 2>&1 || exit 1

echo; echo "restore 0 Directory"
restore0Dir -processor

echo; echo "renumberMesh"
time $parEx renumberMesh -constant -overwrite -parallel $fileHandler > $logDir/20_renumberMesh.log 2>&1 || exit 1

echo; echo "potentialFoam"
time $parEx potentialFoam -initialiseUBCs -parallel $fileHandler > $logDir/30_potentialFoam.log 2>&1 || exit 1

echo; echo "applyBoundaryLayer"
time $parEx applyBoundaryLayer -ybl "0.0450244" -parallel $fileHandler > $logDir/40_applyBoundaryLayer.log 2>&1 || exit 1

echo; echo $solverRANS
time $parEx $solverRANS -parallel $fileHandler > $logDir/50_$solverRANS.$TIMESTAMP.log 2>&1 || exit 1
echo "... done!"
