var searchData=
[
  ['validate_0',['validate',['../classNeoFOAM_1_1SpalartAllmarasDDES.html#a3c0ce97c52d3cc20099747f4728acda0',1,'NeoFOAM::SpalartAllmarasDDES']]],
  ['vec3_1',['vec3',['../pressureVelocityCoupling_8hpp.html#ae261b7f2859c508a432e8a334ad179d2',1,'Vec3:&#160;pressureVelocityCoupling.hpp'],['../spalartAllmarasDDES_8hpp.html#ae261b7f2859c508a432e8a334ad179d2',1,'Vec3:&#160;spalartAllmarasDDES.hpp']]],
  ['vectorvaluetype_2',['VectorValueType',['../classNeoN_1_1finiteVolume_1_1cellCentred_1_1ViscousStressOperator.html#aef41879bdde8cb25c6876a628c047a2f',1,'NeoN::finiteVolume::cellCentred::ViscousStressOperator']]],
  ['viscousstress_3',['viscousstress',['../classNeoN_1_1finiteVolume_1_1cellCentred_1_1GaussViscousStress.html#a39a6fff372709f44e23002c785bcf338',1,'NeoN::finiteVolume::cellCentred::GaussViscousStress::viscousStress(const VolumeField&lt; scalar &gt; &amp;nu, const VolumeField&lt; scalar &gt; &amp;nut, const VolumeField&lt; Tensor &gt; &amp;gradU, const dsl::Coeff operatorScaling) const'],['../classNeoN_1_1finiteVolume_1_1cellCentred_1_1GaussViscousStress.html#aef1aeb10d49f4dde7eb45f5b11ee9eb6',1,'NeoN::finiteVolume::cellCentred::GaussViscousStress::viscousStress(VolumeField&lt; Vec3 &gt; &amp;result, const VolumeField&lt; scalar &gt; &amp;nu, const VolumeField&lt; scalar &gt; &amp;nut, const VolumeField&lt; Tensor &gt; &amp;gradU, const dsl::Coeff operatorScaling) const'],['../classNeoN_1_1finiteVolume_1_1cellCentred_1_1GaussViscousStress.html#a4f03d108312e6603e46276519569bc83',1,'NeoN::finiteVolume::cellCentred::GaussViscousStress::viscousStress(Vector&lt; Vec3 &gt; &amp;result, const VolumeField&lt; scalar &gt; &amp;nu, const VolumeField&lt; scalar &gt; &amp;nut, const VolumeField&lt; Tensor &gt; &amp;gradU, const dsl::Coeff operatorScaling) const']]],
  ['viscousstressoperator_4',['viscousstressoperator',['../classNeoN_1_1finiteVolume_1_1cellCentred_1_1ViscousStressOperator.html',1,'NeoN::finiteVolume::cellCentred::ViscousStressOperator'],['../classNeoN_1_1finiteVolume_1_1cellCentred_1_1ViscousStressOperator.html#a3ba793d8264dda9fc8fd4b3de3635364',1,'NeoN::finiteVolume::cellCentred::ViscousStressOperator::ViscousStressOperator(const ViscousStressOperator &amp;other)'],['../classNeoN_1_1finiteVolume_1_1cellCentred_1_1ViscousStressOperator.html#a07ebbd94226d9727b0cbc4ec3e6c3244',1,'NeoN::finiteVolume::cellCentred::ViscousStressOperator::ViscousStressOperator(dsl::Operator::Type termType, const VolumeField&lt; scalar &gt; &amp;nu, const VolumeField&lt; scalar &gt; &amp;nut, const VolumeField&lt; Tensor &gt; &amp;gradU, Input input)'],['../classNeoN_1_1finiteVolume_1_1cellCentred_1_1ViscousStressOperator.html#ad0553ce159e2562a34acd2af91417542',1,'NeoN::finiteVolume::cellCentred::ViscousStressOperator::ViscousStressOperator(dsl::Operator::Type termType, const VolumeField&lt; scalar &gt; &amp;nu, const VolumeField&lt; scalar &gt; &amp;nut, const VolumeField&lt; Tensor &gt; &amp;gradU, std::unique_ptr&lt; ViscousStressOperatorFactory &gt; viscousOp)'],['../classNeoN_1_1finiteVolume_1_1cellCentred_1_1ViscousStressOperator.html#af703988ee63d7d4f0b16d22f700f7086',1,'NeoN::finiteVolume::cellCentred::ViscousStressOperator::ViscousStressOperator(dsl::Operator::Type termType, const VolumeField&lt; scalar &gt; &amp;nu, const VolumeField&lt; scalar &gt; &amp;nut, const VolumeField&lt; Tensor &gt; &amp;gradU)']]],
  ['viscousstressoperator_2ehpp_5',['viscousStressOperator.hpp',['../viscousStressOperator_8hpp.html',1,'']]],
  ['viscousstressoperatorfactory_6',['viscousstressoperatorfactory',['../classNeoN_1_1finiteVolume_1_1cellCentred_1_1ViscousStressOperatorFactory.html',1,'NeoN::finiteVolume::cellCentred::ViscousStressOperatorFactory'],['../classNeoN_1_1finiteVolume_1_1cellCentred_1_1ViscousStressOperatorFactory.html#a3aabde670f56aabc5dbe8ef2f5a5c782',1,'NeoN::finiteVolume::cellCentred::ViscousStressOperatorFactory::ViscousStressOperatorFactory()']]]
];
