#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------
touch cavity.foam
restore0Dir

runApplication blockMesh

# runApplication ../../build/profiling/bin/neoIcoFoam
# runApplication icoFoam

#------------------------------------------------------------------------------
