#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------
touch cavity.foam
restore0Dir

runApplication blockMesh
runApplication decomposePar

# mpirun -np 4 neofoam solver icofoam -parallel
# runApplication neofoam solver icofoam
runParallel "neofoam solver icofoam"


#runApplication ../../build/profiling/bin/icoNeoFoam
# runApplication icoFoam

#------------------------------------------------------------------------------
