# SPDX-License-Identifier: Unlicense
# SPDX-FileCopyrightText: 2023 FoamAdapter authors

# Generated by CxxThirdParty.cmake.in

include(cmake/CPM.cmake)

if(FoamAdapter_BUILD_TESTS OR FoamAdapter_BUILD_BENCHMARKS)
  cpmaddpackage(NAME Catch2 GITHUB_REPOSITORY catchorg/Catch2 VERSION 3.4.0)
endif()

if(FOAMADAPTER_NEON_VIA_CPM)
  if(NOT DEFINED FOAMADAPTER_NEON_VERSION)
    set(FOAMADAPTER_NEON_VERSION
        "c0cb11896fe5621f19ff3693360dbcca77e1e576"
        CACHE INTERNAL "")
  endif()

  cpmaddpackage(
    NAME
    NeoN
    GITHUB_REPOSITORY
    exasim-project/NeoN
    GIT_TAG
    ${FOAMADAPTER_NEON_VERSION}
    SYSTEM
    YES
    "Kokkos_ENABLE_CUDA ${Kokkos_ENABLE_CUDA}"
    "Kokkos_ENABLE_HIP ${Kokkos_ENABLE_HIP}")
endif()
