name: Build NeoN on MacOs
run-name: 'Build workflow'

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    types:
      - synchronize
      - opened
  schedule:
    - cron: "* 0 * * 0"

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  OMPI_MCA_rmaps_base_oversubscribe: 1

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: ${{!contains(github.event.pull_request.labels.*.name, 'Skip-build')}}
    name: Build NeoN on MacOs
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - CC: gcc
            CXX: g++
        preset: ["develop" ]
    runs-on: macos-latest
    steps:
     - name: Checkout to repository
       uses: actions/checkout@v4

     - name: Set up cache
       uses: actions/cache@v4
       if: ${{!contains(github.event.pull_request.labels.*.name, 'Skip-cache')}}
       with:
         path: build
         key: macos_build_PR_${{ github.event.pull_request.number }}_${{matrix.compiler.CC}}_${{matrix.preset}}

     - name: Install dependencies
       run: |
         /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
         brew install ninja cmake libomp

     - name: Get versions
       run: |
         clang --version
         ninja --version
         cmake --version

     - name: Build NeoN
       run: |
         CC=${{matrix.compiler.CC}} \
         CXX=${{matrix.compiler.CXX}} \
         cmake --preset ${{matrix.preset}} \
           -DNeoN_BUILD_TESTS=ON \
           -DNeoN_DEVEL_TOOLS=OFF \
           -DCMAKE_PREFIX_PATH=/opt/homebrew/opt/libomp/ \
           -DNeoN_ENABLE_MPI_WITH_THREAD_SUPPORT=OFF
         cmake --build  --preset ${{matrix.preset}}

     - name: Execute unit tests NeoN
       run: |
         ctest --preset ${{matrix.preset}}
