name: Build documentation

env:
  PR_NUMBER: ${{ github.event.number }}

on:
  pull_request:
    types: [opened, synchronize, closed]

  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: System packages
      run: sudo apt-get update && sudo apt-get install -y doxygen texlive-font-utils

    - name: Set up OpenFOAM
      uses: gerlero/setup-openfoam@v1
      with:
        openfoam-version: 2412

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - uses: pyvista/setup-headless-display-action@v3

    - name: Install project + docs extras
      run: |
        python -m pip install --upgrade pip
        pip install ".[docs]"

    - name: Build docs
      run: |
        sphinx-build -b html ./doc ./docs_build/
        cp -r doc/_build/ docs_build/doxygen
        touch ./docs_build/.nojekyll

    # 1. PREVIEW BUILD (per PR)
    - name: Deploy PR Build
      if: ${{ github.event_name == 'pull_request' && !github.event.pull_request.merged && github.event.pull_request.user.login != 'dependabot[bot]' }}
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs_build
        target-folder: Build_PR_${{ env.PR_NUMBER }}

    # 2. VERSIONED BUILD (tags)
    - name: Deploy Versioned Build
      if: ${{ github.ref_type == 'tag' }}
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs_build
        target-folder: ${{ github.ref_name }}

    # 3. DEPLOY FOR MAIN (stable)
    - name: Deploy Main
      if: >
        github.event.pull_request.merged &&
        github.event.pull_request.base.ref == 'main'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs_build
        target-folder: main

    # 4. DEPLOY FOR DEVELOP (dev preview)
    - name: Deploy Develop
      if: >
        github.event.pull_request.merged &&
        github.event.pull_request.base.ref == 'develop'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs_build
        target-folder: develop

    - name: Comment PR
      if: ${{ github.event_name == 'pull_request' && github.event.pull_request.user.login != 'dependabot[bot]' }}
      uses: thollander/actions-comment-pull-request@v2
      with:
        message: |
          Deployed test documentation to https://exasim-project.com/NeoFOAM/Build_PR_${{ env.PR_NUMBER }}
        comment_tag: build_url

    - name: Echo Build PR URL
      if: ${{ github.event_name == 'pull_request' && github.event.pull_request.user.login != 'dependabot[bot]' }}
      run: echo "Deploy to https://exasim-project.com/NeoFOAM/Build_PR_${{ env.PR_NUMBER }}"
