name: Static checks
run-name: Static checks

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-compilation-db:
    if: "!contains(toJson(github.event.pull_request.labels.*.name), 'Skip-build')"
    name: Build with IWYU
    runs-on: ubuntu-24.04
    steps:
      - name: Determine branch
        run: |

          # Detect current branch of NeoFOAM
          NEOFOAM_BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF_NAME}}"
          echo "Using NeoFOAM branch: $NEOFOAM_BRANCH"
          echo "NEOFOAM_BRANCH=$NEOFOAM_BRANCH" >> $GITHUB_ENV

          # Define remote repo URL
          REPO_URL="https://github.com/exasim-project/NeoN"

          echo "Checking if branch '$NEOFOAM_BRANCH' exists in NeoN..."

          # Query exact match: refs/heads/<branch>
          if git ls-remote --exit-code --heads "$REPO_URL" "refs/heads/${NEOFOAM_BRANCH}" >/dev/null 2>&1; then
            echo "NeoN branch exists: $NEOFOAM_BRANCH"
            echo "NEON_BRANCH=$NEOFOAM_BRANCH" >> $GITHUB_ENV
          else
            echo "NeoN branch '$NEOFOAM_BRANCH' does not exist. Falling back to 'develop'."
            echo "NEON_BRANCH=develop" >> $GITHUB_ENV
          fi
    - uses: actions/checkout@v4

    - name: Add repos
      run: |
        sudo add-apt-repository 'deb https://dl.openfoam.com/repos/deb noble main'
        sudo apt-key add .github/workflows/pubkey.gpg

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install \
           ninja-build \
           iwyu \
           clang-16 \
           libomp-16-dev \
           libopenmpi-dev \
           openmpi-bin \
           openfoam2406-dev


    - name: Create Compilation Database
      run: |
        source /usr/lib/openfoam/openfoam2406/etc/bashrc || true
        CC=clang \
        CXX=clang++ \
        cmake --preset develop \
          -DNEOFOAM_DEVEL_TOOLS=OFF \
          -DNEOFOAM_BUILD_BENCHMARKS=OFF \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
          -DNEOFOAM_ENABLE_MPI_WITH_THREAD_SUPPORT=OFF \
          -DNEOFOAM_NEON_VERSION=${{ env.NEON_BRANCH }} \
          -DNEOFOAM_ENABLE_IWYU=ON
        cmake --build --preset develop
    - uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: build
  clang-tidy-check:
    name: Clang-tidy Check
    runs-on: ubuntu-24.04
    needs: [build-compilation-db]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true # Recursively clone submodules

    - name: Add repos
      run: |
        sudo add-apt-repository 'deb https://dl.openfoam.com/repos/deb noble main'
        sudo apt-key add .github/workflows/pubkey.gpg

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install \
           clang-tidy-16 \
           libomp-16-dev \
           libopenmpi-dev \
           openmpi-bin \
           openfoam2406-dev

    - uses: actions/download-artifact@v4
      with:
        name: build-artifact
        path: build

    - name: Run clang-tidy
      run: |
        # Create list of .cpp files belonging to this repository
        git ls-files | grep -E "\.(cpp)" > pattern
        # Create list of .cpp files that are in this repository and part of the
        # compilation database
        # also filters out " at the begin and end of the filename
        jq ".[] | .file" build/develop/compile_commands.json \
          | sed 's/^"\(.*\)"$/\1/' \
          | grep -F -f pattern - > files
        # run clang-tidy on all specified files
        grep -v "examples/" files > files_wo_examples
        clang-tidy-16 --fix --extra-arg=-w -p build/develop $(cat files_wo_examples)

    - name: Check for fixes
      run: |
        if [[ $(git ls-files -m | wc -l) -eq 0 ]]; then
          exit 0
        fi
        echo "There are fixes available from clang-tidy."
        echo "Please use your local clang-tidy or apply the following patch:"
        git diff -p
        exit 1
  pre-commit-run:
    name: Pre-commit run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true # Recursively clone submodules
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install \
           pre-commit python3-identify
        pre-commit install
    - name: Run pre-commit on all files
      run: pre-commit run --all --color always --verbose
    - name: check for todo fixme note
      run: |
        NTODOS="$(grep -r 'TODO DONT MERGE' --exclude-dir=.github | wc -l)"
        echo "Found $NTODOS TODO DONT MERGE notes"
        ! grep -q -r "TODO DONT MERGE" --exclude-dir=.github
