name: Mirror to LRZ Gitlab

on:
  push:
    branches: [develop, main, clean_ci]
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  mirror:
    name: mirror to LRZ Gitlab
    runs-on: ubuntu-latest
    timeout-minutes: 1440 # 24 hours

    # Only run if the 'Skip-build' label is not present on a PR
    if: "!contains(toJson(github.event.pull_request.labels.*.name), 'Skip-build')"

    env:
      LRZ_GROUP: greole
      LRZ_HOST: gitlab-ce.lrz.de
      REPO_NAME: ${{ github.event.repository.name }}
      MAX_WAIT_MINUTES: 1440
      LRZ_GITLAB_PROJECT_TOKEN: ${{ secrets.GITLAB_PROJECT_TOKEN }}
      LRZ_GITLAB_TRIGGER_TOKEN: ${{ secrets.LRZ_GITLAB_TRIGGER_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push commit to LRZ GitLab
        run: |
          echo "branch ${{ github.ref_name }}"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote add lrz https://oauth2:${LRZ_GITLAB_PROJECT_TOKEN}@${LRZ_HOST}/${LRZ_GROUP}/${REPO_NAME}.git
          git fetch origin ${{ github.ref_name }}
          git checkout -B ${{ github.ref_name }} origin/${{ github.ref_name }}
          git reset --hard origin/${{ github.ref_name }}
          git push --force lrz HEAD:refs/heads/${{ github.ref_name }}

  benchmark:
    name: Benchmark FoamAdapter on GPU
    runs-on: ubuntu-latest
    timeout-minutes: 1440 # 24 hours

    needs: [mirror]
    # if: contains(toJson(github.event.pull_request.labels), 'benchmark')

    env:
      LRZ_GROUP: greole
      LRZ_HOST: gitlab-ce.lrz.de
      REPO_NAME: ${{ github.event.repository.name }}
      BRANCH: ${{ github.ref_name }}
      LRZ_GITLAB_PROJECT_TOKEN: ${{ secrets.GITLAB_PROJECT_TOKEN }}
      LRZ_GITLAB_TRIGGER_TOKEN: ${{ secrets.LRZ_GITLAB_TRIGGER_TOKEN }}
      MAX_WAIT_MINUTES: 1440

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Trigger LRZ GitLab CI pipeline for benchmarking
        id: trigger
        run: |
          ./ci/github/trigger_pipeline.sh \
            "${BRANCH}" \
            "variables[TRIGGER_SOURCE]=${{ github.event.repository.name }}" \
            "variables[BENCHMARK]=true"