# Source: https://github.com/exasim-project/NeoFOAM/blob/3c64f2ca7d0f108e3f4c012c6a3ca8a5341184ed/.github/workflows/windows.yml

name: Build NeoFOAM Windows

on: workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ (github.head_ref && github.ref) || github.run_id }}
  cancel-in-progress: true

jobs:
  windows_msvc:
    if: ${{!contains(github.event.pull_request.labels.*.name, 'Skip-build')}}
    name: msvc
    runs-on: [windows-latest]
    steps:
    - name: Checkout the latest code (shallow clone)
      uses: actions/checkout@v4

    - uses: ilammy/msvc-dev-cmd@v1
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: configure
      run: |
        cmake --preset develop -DKokkos_DIR="D:/dev/Kokkos/lib/cmake/Kokkos" -DNEOFOAM_DEVEL_TOOLS=OFF -DNEOFOAM_ENABLE_MPI_SUPPORT=OFF
      shell: cmd

    - name: build
      run: |
        cmake --build --preset develop
      shell: cmd

    - name: test
      run: |
        cmake --build --preset develop --target test
      shell: cmd
